theme: jekyll-theme-slate
title: Tomasz Bednarz
description: Personal Website
twitter_username: tomaszbednarz

include:
 - _pages

plugins:
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-gist
 - jemoji
 - jekyll-feed
 - jekyll-seo-tag

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true