baseurl: "/"
title: Tomasz Bednarz
description: Personal Website
author: 
  name: Tomasz Bednarz
  email: firstname.surname@gmail.com
twitter_username: tomaszbednarz

include:
 - _pages

markdown: kramdown
# theme: minima

plugins:
# - jekyll-paginate
# - jekyll-sitemap
# - jekyll-gist
# - jemoji
 - jekyll-feed
 - jekyll-seo-tag
 - liquid

#defaults:
  # _posts
#  - scope:
#      path: ""
#      type: posts
#    values:
#      layout: single
#      author_profile: true
#      read_time: true
#      comments: true
#      share: true
#      related: true
  # _pages
#  - scope:
#      path: "_pages"
#      type: pages
#    values:
#      layout: single
#      author_profile: true
